name: "yolov8m"
variant: "yolov8m.pt"
imgsz: 224
batch: 8
epochs: 100
conf_threshold: 0.75
num_classes: 5
class_names:
  - "joint_space"
  - "medial_femur"
  - "lateral_femur"
  - "medial_tibia"
  - "lateral_tibia"
